const crypto = require("crypto");

/**
 * authOwner middleware
 *
 * Verifies the JWT token that was generated by ownerController using the same
 * native HMAC-SHA256 approach (no external library needed).
 *
 * Expects: Authorization: Bearer <token>
 *
 * On success: attaches req.owner = { id, email } and calls next()
 * On failure: responds with 401 Unauthorized
 */
function authOwner(req, res, next) {
  const authHeader = req.headers["authorization"] || req.headers["Authorization"];

  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return res.status(401).json({ error: "Unauthorized: No token provided" });
  }

  const token = authHeader.slice(7); // Remove "Bearer "
  const parts = token.split(".");

  if (parts.length !== 3) {
    return res.status(401).json({ error: "Unauthorized: Malformed token" });
  }

  const [header, body, signature] = parts;

  // Re-compute the expected signature using the same secret
  const secret = process.env.JWT_SECRET || "luxestay_fallback_secret_key";
  const expectedSignature = crypto
    .createHmac("sha256", secret)
    .update(`${header}.${body}`)
    .digest("base64url");

  // Constant-time comparison to prevent timing attacks
  if (
    signature.length !== expectedSignature.length ||
    !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expectedSignature))
  ) {
    return res.status(401).json({ error: "Unauthorized: Invalid token signature" });
  }

  // Decode the payload
  let payload;
  try {
    payload = JSON.parse(Buffer.from(body, "base64url").toString("utf8"));
  } catch {
    return res.status(401).json({ error: "Unauthorized: Could not parse token" });
  }

  // Ensure this is an owner token (not a guest/user token)
  if (payload.role !== "owner") {
    return res.status(403).json({ error: "Forbidden: Owner access required" });
  }

  // Attach decoded identity to the request for use in controllers
  req.owner = { id: payload.id, email: payload.email };
  next();
}

module.exports = authOwner;
